名前: ネコとスコア
ステージ:
  スクリプト: stage.sbk
  変数:
    スコア: 0
  リスト:
    記録: []
スプライト:
  - 名前: ネコ
    スクリプト: neko.sbk
    x: 0
    y: 0
    コスチューム:
      - 名前: 笑顔
        ファイル: neko-egao.svg
    音:
      - 名前: ピ
        ファイル: pi.wav
